name: Generate Contribution Graph Animation

on:
  schedule:
    - cron: "0 */24 * * *"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2.2.1
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: push github-contribution-grid-snake.svg to the master branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          keep_history: true
          target_branch: master
          build_dir: dist
          committer: ALI <1416978277@qq.com>
          author: ALI <1416978277@qq.com>
          commit_message: Generate Contribution Graph Animation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
